import { Banner, Contact, FAQ, Footer, Navbar, Product } from '#/components'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es' className='scroll-smooth'>
      <body className={`${inter.className} min-h-screen`}>
        <div>
          {/* <Banner /> */}
          <Navbar />
          {children}
        </div>
        <Product />
        <FAQ />
        <Contact />
        <Footer />
      </body>
    </html>
  )
}
